### ISSUE TITLE
关于更多功能的建议

### ISSUE THREAD

**Issue by M1hono** [Maplefsnow/MapBotv4#2]
您好，请问可以更新一个可以在配置文件分别增加“群向服务器投递信息”和“服务器向群投递信息”的开关吗

**Comment by Maplefsnow** [comment]
你好。

非常好的建议！我将会在下个版本添加此功能。

谢谢你的宝贵建议。

**Comment by Maplefsnow** [comment]
你好，此功能已在提交 https://github.com/Maplefsnow/MapBotv4/commit/2519f6e87b3af9c28e3d518d98c7416bf2a73bef 和发行版 [v0.9.0-beta](https://github.com/Maplefsnow/MapBotv4/releases/tag/v0.9.0-beta) 中新增。

如还有其他建议请提交新的 issue，再次感谢你的建议。
