### ISSUE TITLE
戳一戳的新功能提议

### ISSUE THREAD

**Issue by L1Xu4n** [Maplefsnow/MapBotv4#21]
群内玩家被戳，同时这个玩家游戏在线的话，可以实现一些游戏内效果，比如有文字提示，粒子效果，收到一点伤害之类的？

**Comment by hetaoawa** [comment]
赞同，可以提升趣味性，但如果有人刷屏可能会影响玩家游玩
且某些协议下无法收取戳一戳消息，实现较为繁琐，也许小枫不太可能会添加

**Comment by Maplefsnow** [comment]
我查一下 mirai 的开发文档，看看有没有类似的功能支持

**Comment by hetaoawa** [comment]
某些框架下无法接收戳一戳消息
(如 手表协议
此时戳一戳功能无法生效
其他协议下也会出现丢失的情况
综合建议是:很有意思，~~但小枫可能能写吐（~~

**Comment by Maplefsnow** [comment]
已经找到了，在写了

**Comment by Maplefsnow** [comment]
戳一戳功能已经基本开发完毕，请期待最新版本

**Comment by Maplefsnow** [comment]
戳一戳已在0.15.0添加
