### ISSUE TITLE
无法在群内使用 #pay 命令

### ISSUE THREAD

**Issue by hetaoawa** [Maplefsnow/MapBotv4#23]
在群内使用#pay命令会显示未在本群开启
且后台会有报错
请修复此功能或将报错改为info而不是抛出warn或不显示
![image](https://user-images.githubusercontent.com/79517899/210785530-bbb1741d-ada6-416c-8330-810df3349726.png)
插件版本:Mapbot-test-v2

**Comment by Maplefsnow** [comment]
已在预发布版修复，请等待最新发布版

**Comment by Maplefsnow** [comment]
不确定是否已经在 0.14.1 修复，请及时反馈

**Comment by Maplefsnow** [comment]
将在下个发布版修复此问题

**Comment by Maplefsnow** [comment]
fixed on 0.15.0
