### ISSUE TITLE
普通玩家在群内使用#deleteid此类的管理员命令时会在后台抛出warn

### ISSUE THREAD

**Issue by hetaoawa** [Maplefsnow/MapBotv4#24]
普通玩家在群内使用#deleteid此类的管理员命令时会显示你没有使用此命令的权限
且后台会有报错
请将报错改为info而不是抛出warn或不显示
![image](https://user-images.githubusercontent.com/79517899/210786247-7f4dd40c-8596-4a78-8c55-b55eca037c63.png)
插件版本:Mapbot-test-v2

**Comment by Maplefsnow** [comment]
已在预发布版修复，请等待最新发布版

**Comment by Maplefsnow** [comment]
solved in 0.14.1
