### ISSUE TITLE
在使用#禁言命令时会提示未找到该玩家，但玩家确实存在

### ISSUE THREAD

**Issue by hetaoawa** [Maplefsnow/MapBotv4#25]
![image](https://user-images.githubusercontent.com/79517899/210786510-039d5072-fc1a-4c46-85d7-a46d776ab5a3.png)
![image](https://user-images.githubusercontent.com/79517899/210787234-a1082786-e32a-4a80-90b8-e85e535c22dc.png)
如图，在群内使用#禁言 命令时会显示未找到该玩家
且后台会有报错
请将报错改为info而不是抛出warn或不显示

**Comment by Maplefsnow** [comment]
此 bug 已在与发布版修复，请等待最新发布版

**Comment by Maplefsnow** [comment]
solved in 0.14.1
