### ISSUE TITLE
未知问题抛出error（麻烦小枫看明白自己改标题吧，我看不懂呜呜）

### ISSUE THREAD

**Issue by hetaoawa** [Maplefsnow/MapBotv4#26]
如图，正好是整点报的，所以我怀疑是不是什么定时任务，到提交此issue为止，还没有第二次出现此问题
![image](https://user-images.githubusercontent.com/79517899/211146211-358caad5-cad8-4775-b9c6-42047aefc6a2.png)
插件版本:mapbotv4-0.14.0beta-1.18
由于同一账号同时只能登陆同一服务端，所以无法测试mapbotv4-0.14.0beta-1.19是否会有同样问题，但我猜应该有（

**Comment by Maplefsnow** [comment]
这是一个弃用功能（内群自动踢人），无特殊情况请不要开启
