### ISSUE TITLE
请问无法登陆如何解决

### ISSUE THREAD

**Issue by L1Xu4n** [Maplefsnow/MapBotv4#3]
作者大大
我之前在一台服务器上正常使用，近期升级服务器换到了另一台也可以正常使用，因为暂时需要在自己的手机上登陆了机器人账号，然后mapbot就登不上去了，后台一直提示登陆中，我已经尝试了先登上其他腾讯网站避免安全验证，又尝试了完整卸载插件然后重装，都登不上，怎么办？
服务端paper1.18.2，mapbot0.7.0

**Comment by Maplefsnow** [comment]
首先建议升级到最新版 Mapbot_v0.9.0-beta

其次在服务端未退出bot的情况下用手机设备登录bot账号确实会产生问题，建议将手机端的bot账号彻底登出再在服务端尝试登陆，如仍无法登录可尝试在**电脑端**登录bot账号的情况下从服务端登陆账号

我没有遇到过反复登录也登陆不上的情况，也可能是设备锁的原因

**Comment by L1Xu4n** [comment]
您好，我最近比较忙，23号左右给您回复一下解决情况，烦请您有时间看看，另外我最近才注册github，不太了解社区规则，有什么做的不对的还请您谅解下

**Comment by Maplefsnow** [comment]
好的，我会持续关注此 issue

**Comment by L1Xu4n** [comment]
您好，我已经升级到了0.9.0，我尝试了在服务器登陆qq之后，mirai可以成功登陆，但mapbot仍然无法登陆，请问需要指定登陆协议吗？比如把默认Android phone改为Android pad or Watch？
另外我昨天看到您在mcbbs上的帖子的插件版本还停留在0.7.0还请您注意下哈

**Comment by Maplefsnow** [comment]
mcbbsv3我有点懒得改了，我目前在维护mcbbsv4的帖子，是mcbbs的新版测试论坛

指定登陆协议或许有用，我看看试着在配置文件加上这一项

**Comment by L1Xu4n** [comment]
更新到新版本后我可以登陆了，感谢开发
