### ISSUE TITLE
请问能否改进无数据库模式？

### ISSUE THREAD

**Issue by L1Xu4n** [Maplefsnow/MapBotv4#4]
作者大大：
我不太会用数据库所有就没有安装，如果不安装数据库在qq群内发送绑定命令就会报代码，请问能否改进？

**Comment by Maplefsnow** [comment]
因为需要存储玩家信息所以必须使用额外的数据库，在不使用 MySQL 的情况下不需要额外安装数据库

请提供报错信息

**Comment by L1Xu4n** [comment]
更新到新版本后，报错问题解决了，感谢开放
