### ISSUE TITLE
新功能的请求

### ISSUE THREAD

**Issue by L1Xu4n** [Maplefsnow/MapBotv4#5]
1.在q群内支持执行控制台命令，并返回控制台的消息
2.添加一个#info命令显示服务器的状态如tps，区块数实体数等
3.添加一个reload命令用来调试autoreply
4.autoreply支持更多的判定模式比如包含某字符
5.autoreply在config中添加取消控制台提示的功能
6.白名单功能支持绑定同一个人的游戏小号，比如同一qq但是绑定多个游戏账号
7.#list命令支持显示基岩版玩家
希望作者大大能采纳并尽快更新吧

**Comment by Maplefsnow** [comment]
感谢你的宝贵建议！

我会将此 issue 作为一个 todo list，在此 list 完成前请保持联系，以让我能更好地作出修改并修复问题。

**Comment by L1Xu4n** [comment]
8.添加白名单与群昵称绑定，比如绑定游戏id后自动修改群id，如检测到此人改动id予以警告并自动改回，添加#nick允许他自己设置昵称，比如：
Notch绑定了名字则群昵称为 Notch
Notch绑定了名为123的昵称则群昵称为 Notch | 123

**Comment by Maplefsnow** [comment]
你好，你所列的3至5条已于0.12.0版本完工

第1条需要帮助，我没有找到能获取命令返回值的方法

第7条中的基岩版玩家是指什么？

第2，6两条预计将于0.13.0添加，请保持关注

**Comment by L1Xu4n** [comment]
1.抱歉我没有开发插件的经验不能提供实在的帮助，我觉得是否可以在执行命令时创建一个虚拟玩家代替控制台发送命令，获取玩家的命令返回值，从而避免无法获取控制台的命令返回值？
7.geyser是一个插件，它作为je和be的桥梁通过翻译数据包的方法工作，旨在让基岩版玩家加入java服务器，floodgate是geyser的附属插件，floodgate提供了api告诉第三方插件哪些玩家是基岩版，#list可以像显示正常玩家一样显示基岩版玩家，但是我希望他能标记出哪些玩家是基岩版

**Comment by Maplefsnow** [comment]
以上提议除7，8两条外均已采纳，请关注最新版本
