### ISSUE TITLE
玩家死亡后后台警告

### ISSUE THREAD

**Issue by L1Xu4n** [Maplefsnow/MapBotv4#6]
![image](https://user-images.githubusercontent.com/106089276/177504080-da00963b-75c7-422c-93d3-5c8087a52274.png)
请问能删除或对这个警告添加屏蔽吗？

**Comment by Maplefsnow** [comment]
你好，考虑到 mapbot 的专业性，此功能目前已停止维护。

新版本移除了货币换死亡不掉落和急迫的功能，这些功能均移交新的插件处理，这是这个插件的一个**测试版本**：https://7v40bl-my.sharepoint.com/:u:/g/personal/clpublic_7v40bl_onmicrosoft_com/ET3PAmzf-f9NooCxHUjeiEYBc1-2F1BxGpXmnDm7UyVLeA?e=dzPMcw

因此插件尚未成熟故还没有公布，如确有需要请在升级mapbot后加装此插件。

**Comment by L1Xu4n** [comment]
你好，我使用的是最新版本，但这个功能的相关命令似乎依然存在？
并且如何关闭这个警告？

**Comment by Maplefsnow** [comment]
此报错是因为数据库中找不到死亡玩家的信息，目前最新版本是 https://github.com/Maplefsnow/MapBotv4/releases/tag/v0.10.0-beta （我刚发布的），请使用这一版本并配合 ExtraFuncPurchase 插件。

如仍有报错可继续在此回复。
